# Generated by Django 3.2.3 on 2021-07-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('titulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[('T', 'Terror'), ('D', 'Drama'), ('C', 'Comedia'), ('A', 'Accion'), ('S', 'Suspenso')], max_length=1)),
                ('idioma', models.CharField(choices=[('I', 'Ingles'), ('E', 'Español')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=20)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.pelicula')),
            ],
        ),
    ]
