# Generated by Django 3.2.5 on 2021-07-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('IdCliente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('idSala', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sinopsis',
            fields=[
                ('descripcion', models.TextField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariocliente',
            name='id',
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='IdCliente',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.sala')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='AppCine.sinopsis'),
            preserve_default=False,
        ),
    ]
