# Generated by Django 3.2.5 on 2021-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0002_auto_20210708_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='sinopsis',
        ),
        migrations.AddField(
            model_name='reservas',
            name='hora',
            field=models.CharField(default=True, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='edad',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sinopsis',
        ),
    ]
