# Generated by Django 3.2.5 on 2021-07-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0003_auto_20210708_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartelera',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.RemoveField(
            model_name='usuariocliente',
            name='pelicula',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='UsuarioCliente',
        ),
    ]
