# Generated by Django 3.2.5 on 2021-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0004_auto_20210709_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='edad',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
