# Generated by Django 3.2.5 on 2021-07-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0005_pelicula_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('idSala', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('IdCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=50)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCine.pelicula')),
            ],
        ),
    ]
