# Generated by Django 3.2.5 on 2021-07-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0007_cartelera_entrada_promocion_reservas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
