# Generated by Django 3.2.5 on 2021-07-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0008_rename_reservas_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Terror', 'Terror'), ('Drama', 'Drama'), ('Comedia', 'Comedia'), ('Accion', 'Accion'), ('Suspenso', 'Suspenso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(choices=[('Ingles', 'Ingles'), ('Español', 'Español')], max_length=20),
        ),
    ]
