# Generated by Django 3.2.5 on 2021-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0010_remove_usuariocliente_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=15),
        ),
    ]
