# Generated by Django 3.2.4 on 2021-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine', '0011_alter_reserva_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='img',
            field=models.ImageField(default=True, upload_to='pics'),
            preserve_default=False,
        ),
    ]
